# **Data Practicum II**

**Investigating the Co-occurrence of Supply Chain Gaps that are Driven by Business Closures in the US**

### Week 2: Data: Collection, Data Preparation (Data Cleaning, Feature Engineering, Data Merging)

# Data

**US Census.gov API**: Business Closures Data from the Business Dynamics Statistics (BDS) capturing data from 1978 - 2023 with 28 attributes on establishments and exits of firms across different states and territories (56), across sectors (19) and across different firm age categories (12). Total number of observations in the data = 534,888 rows.

In [1]:
import pandas as pd
# Data API URL Link
url_bds = "https://www2.census.gov/programs-surveys/bds/tables/time-series/2023/bds2023_st_sec_fa.csv"
# Importing Data
df_bds = pd.read_csv(url_bds)
# Data Overview
df_bds.head()

,year,st,sector,fage,firms,estabs,emp,denom,estabs_entry,estabs_entry_rate,...,job_destruction_deaths,job_destruction_continuers,job_destruction_rate_deaths,job_destruction_rate,net_job_creation,net_job_creation_rate,reallocation_rate,firmdeath_firms,firmdeath_estabs,firmdeath_emp
0,1978,1,11,a) 0,257,257,1132,566,257,200.000,...,X,X,X,X,1132,200.000,X,X,X,X
1,1978,1,11,b) 1,137,137,528,637,D,D,...,244,121,38.335,57.345,-215,-33.778,47.133,54,54,216
2,1978,1,11,c) 2,X,X,X,X,X,X,...,X,X,X,X,X,X,X,X,X,X
3,1978,1,11,d) 3,X,X,X,X,X,X,...,X,X,X,X,X,X,X,X,X,X
4,1978,1,11,e) 4,X,X,X,X,X,X,...,X,X,X,X,X,X,X,X,X,X

In [2]:
# Getting Data Information
df_bds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534888 entries, 0 to 534887
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   year                         534888 non-null  int64
 1   st                           534888 non-null  int64
 2   sector                       534888 non-null  object
 3   fage                         534888 non-null  object
 4   firms                        534888 non-null  object
 5   estabs                       534888 non-null  object
 6   emp                          534888 non-null  object
 7   denom                        534888 non-null  object
 8   estabs_entry                 534888 non-null  object
 9   estabs_entry_rate            534888 non-null  object
 10  estabs_exit                  534888 non-null  object
 11  estabs_exit_rate             534888 non-null  object
 12  job_creation                 534888 non-null  object
 13  job_creation_births          534888 non-null  object
 14  job_creation_continuers      534888 non-null  object
 15  job_creation_rate_births     534888 non-null  object
 16  job_creation_rate            534888 non-null  object
 17  job_destruction              534888 non-null  object
 18  job_destruction_deaths       534888 non-null  object
 19  job_destruction_continuers   534888 non-null  object
 20  job_destruction_rate_deaths  534888 non-null  object
 21  job_destruction_rate         534888 non-null  object
 22  net_job_creation             534888 non-null  object
 23  net_job_creation_rate        534888 non-null  object
 24  reallocation_rate            534888 non-null  object
 25  firmdeath_firms              534888 non-null  object
 26  firmdeath_estabs             534888 non-null  object
 27  firmdeath_emp                534888 non-null  object
dtypes: int64(2), object(26)
memory usage: 114.3+ MB

**Data Types**: The data types for the numeric variables are set to object and require conversion to int type. Also, sector and fage variables require conversion to object type.

In [3]:
# Feature Engineering: Sector Mapping from Codebook
sector_map = {
    '11': 'Agriculture, Forestry, Fishing and Hunting',
    '21': 'Mining, Quarrying, and Oil and Gas Extraction',
    '22': 'Utilities',
    '23': 'Construction',
    '31-33': 'Manufacturing',
    '42': 'Wholesale Trade',
    '44-45': 'Retail Trade',
    '48-49': 'Transportation and Warehousing',
    '51': 'Information',
    '52': 'Finance and Insurance',
    '53': 'Real Estate and Rental and Leasing',
    '54': 'Professional, Scientific, and Technical Services',
    '55': 'Management of Companies and Enterprises',
    '56': 'Administrative and Support and Waste Management and Remediation Services',
    '61': 'Educational Services',
    '62': 'Health Care and Social Assistance',
    '71': 'Arts, Entertainment, and Recreation',
    '72': 'Accommodation and Food Services',
    '81': 'Other Services (except Public Administration)'
}

# Convert sector to string first
df_bds['sector'] = df_bds['sector'].astype(str)

# Map section values
df_bds['sector_name'] = df_bds['sector'].map(sector_map)

# Feature Engineering: State Mapping from Codebook
state_map = {
    1: 'AL', 2: 'AK',
    4: 'AZ', 5: 'AR',
    6: 'CA', 8: 'CO',
    9: 'CT', 10: 'DE',
    11: 'DC', 12: 'FL',
    13: 'GA', 15: 'HI',
    16: 'ID', 17: 'IL',
    18: 'IN', 19: 'IA',
    20: 'KS', 21: 'KY',
    22: 'LA', 23: 'ME',
    24: 'MD', 25: 'MA',
    26: 'MI', 27: 'MN',
    28: 'MS', 29: 'MO',
    30: 'MT', 31: 'NE',
    32: 'NV', 33: 'NH',
    34: 'NJ', 35: 'NM',
    36: 'NY', 37: 'NC',
    38: 'ND', 39: 'OH',
    40: 'OK', 41: 'OR',
    42: 'PA', 44: 'RI',
    45: 'SC', 46: 'SD',
    47: 'TN', 48: 'TX',
    49: 'UT', 50: 'VT',
    51: 'VA', 53: 'WA',
    54: 'WV', 55: 'WI',
    56: 'WY', 72: 'PR'
}

# Mapping state values
df_bds['state_abbr'] = df_bds['st'].map(state_map)

# Fixing Data Type for Categorical Variables
categorical_cols = ['sector', 'fage', 'state_abbr', 'sector_name']

for col in categorical_cols:
    df_bds[col] = df_bds[col].astype('category')

In [4]:
# Fixing Data Types for Numeric Variables
numeric_cols = [
    'firms',
    'estabs',
    'emp',
    'denom',
    'estabs_entry',
    'estabs_entry_rate',
    'estabs_exit',
    'estabs_exit_rate',
    'job_creation',
    'job_creation_births',
    'job_creation_continuers',
    'job_creation_rate_births',
    'job_creation_rate',
    'job_destruction',
    'job_destruction_deaths',
    'job_destruction_continuers',
    'job_destruction_rate_deaths',
    'job_destruction_rate',
    'net_job_creation',
    'net_job_creation_rate',
    'reallocation_rate',
    'firmdeath_firms',
    'firmdeath_estabs',
    'firmdeath_emp'
]

# Converting to numeric
df_bds[numeric_cols] = df_bds[numeric_cols].apply(
    pd.to_numeric,
    errors='coerce'
)

In [5]:
# Rechecking the Data Types
df_bds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534888 entries, 0 to 534887
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   year                         534888 non-null  int64
 1   st                           534888 non-null  int64
 2   sector                       534888 non-null  category
 3   fage                         534888 non-null  category
 4   firms                        439856 non-null  float64
 5   estabs                       439856 non-null  float64
 6   emp                          439856 non-null  float64
 7   denom                        439123 non-null  float64
 8   estabs_entry                 366896 non-null  float64
 9   estabs_entry_rate            361898 non-null  float64
 10  estabs_exit                  360210 non-null  float64
 11  estabs_exit_rate             355724 non-null  float64
 12  job_creation                 439856 non-null  float64
 13  job_creation_births          366896 non-null  float64
 14  job_creation_continuers      395838 non-null  float64
 15  job_creation_rate_births     361898 non-null  float64
 16  job_creation_rate            434858 non-null  float64
 17  job_destruction              395816 non-null  float64
 18  job_destruction_deaths       360210 non-null  float64
 19  job_destruction_continuers   395838 non-null  float64
 20  job_destruction_rate_deaths  355724 non-null  float64
 21  job_destruction_rate         391330 non-null  float64
 22  net_job_creation             439123 non-null  float64
 23  net_job_creation_rate        434125 non-null  float64
 24  reallocation_rate            392063 non-null  float64
 25  firmdeath_firms              360107 non-null  float64
 26  firmdeath_estabs             360107 non-null  float64
 27  firmdeath_emp                360107 non-null  float64
 28  sector_name                  534888 non-null  category
 29  state_abbr                   534888 non-null  category
dtypes: category(4), float64(24), int64(2)
memory usage: 108.1 MB

**Missing Entries** Data has X and D entries which are identified from https://www.test.census.gov/content/dam/Census/programs-surveys/business-dynamics-statistics/codebook-glossary.pdf given as D = Disclosure Suppression and X = Structurally Missing

In [6]:
# Setting X and D entries as NAs
import numpy as np
df_bds = df_bds.replace(['X', 'D'], np.nan)
df_bds.head()

,year,st,sector,fage,firms,estabs,emp,denom,estabs_entry,estabs_entry_rate,...,job_destruction_rate_deaths,job_destruction_rate,net_job_creation,net_job_creation_rate,reallocation_rate,firmdeath_firms,firmdeath_estabs,firmdeath_emp,sector_name,state_abbr
0,1978,1,11,a) 0,257.0,257.0,1132.0,566.0,257.0,200.0,...,NaN,NaN,1132.0,200.000,NaN,NaN,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",AL
1,1978,1,11,b) 1,137.0,137.0,528.0,637.0,NaN,NaN,...,38.335,57.345,-215.0,-33.778,47.133,54.0,54.0,216.0,"Agriculture, Forestry, Fishing and Hunting",AL
2,1978,1,11,c) 2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",AL
3,1978,1,11,d) 3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",AL
4,1978,1,11,e) 4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",AL

In [7]:
# Checking Missing Entries
df_bds.isnull().sum()

year                                0
st                                  0
sector                              0
fage                                0
firms                           95032
estabs                          95032
emp                             95032
denom                           95765
estabs_entry                   167992
estabs_entry_rate              172990
estabs_exit                    174678
estabs_exit_rate               179164
job_creation                    95032
job_creation_births            167992
job_creation_continuers        139050
job_creation_rate_births       172990
job_creation_rate              100030
job_destruction                139072
job_destruction_deaths         174678
job_destruction_continuers     139050
job_destruction_rate_deaths    179164
job_destruction_rate           143558
net_job_creation                95765
net_job_creation_rate          100763
reallocation_rate              142825
firmdeath_firms                174781
firmdeath_estabs               174781
firmdeath_emp                  174781
sector_name                         0
state_abbr                          0
dtype: int64

In [8]:
# Checking percentge missing
(df_bds.isnull().sum() / len(df_bds)) * 100

year                            0.000000
st                              0.000000
sector                          0.000000
fage                            0.000000
firms                          17.766710
estabs                         17.766710
emp                            17.766710
denom                          17.903748
estabs_entry                   31.406949
estabs_entry_rate              32.341350
estabs_exit                    32.656930
estabs_exit_rate               33.495610
job_creation                   17.766710
job_creation_births            31.406949
job_creation_continuers        25.996096
job_creation_rate_births       32.341350
job_creation_rate              18.701111
job_destruction                26.000209
job_destruction_deaths         32.656930
job_destruction_continuers     25.996096
job_destruction_rate_deaths    33.495610
job_destruction_rate           26.838890
net_job_creation               17.903748
net_job_creation_rate          18.838149
reallocation_rate              26.701852
firmdeath_firms                32.676186
firmdeath_estabs               32.676186
firmdeath_emp                  32.676186
sector_name                     0.000000
state_abbr                      0.000000
dtype: float64

The missing entries across each of the variables does not exceed 33%. Also, the missing entries are present only across the numeric variables and not the identifier and categorical variables of year, st (for state), sector, fage (for firm age), sector_name and sector_abbr

**Imputing**: Time Series Interpolation is applied below within the year, st, sector and fage combination of groups for the base variables with exception made for the derived variables which are computed from the base variables.

In [9]:
# Sorting Data by st, sector, fage and year
df_bds = df_bds.sort_values(['st', 'sector', 'fage', 'year'])


# Getting Base Variables from Codebook
base_vars = [
    'firms',
    'estabs',
    'emp',
    'denom',
    'estabs_entry',
    'estabs_exit',
    'job_creation_births',
    'job_creation_continuers',
    'job_destruction_deaths',
    'job_destruction_continuers',
    'firmdeath_firms',
    'firmdeath_estabs',
    'firmdeath_emp'
]

# Time Series Interpolation of base variables
df_bds[base_vars] = (
    df_bds.groupby(['st', 'sector', 'fage'])[base_vars]
      .transform(lambda x: x.interpolate(limit_direction='both'))
)

/tmp/ipykernel_8379/4161641825.py:24: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_bds.groupby(['st', 'sector', 'fage'])[base_vars]

In [10]:
# Reconstructing the derived variables from base variables
# Job Flow Variables
df_bds['job_creation'] = (
    df_bds['job_creation_births'] +
    df_bds['job_creation_continuers']
)

df_bds['job_destruction'] = (
    df_bds['job_destruction_deaths'] +
    df_bds['job_destruction_continuers']
)

df_bds['net_job_creation'] = (
    df_bds['job_creation'] -
    df_bds['job_destruction']
)

# Rate Variables
df_bds['job_creation_rate_births'] = (
    100 * df_bds['job_creation_births'] / df_bds['denom']
)

df_bds['job_creation_rate'] = (
    100 * df_bds['job_creation'] / df_bds['denom']
)

df_bds['job_destruction_rate_deaths'] = (
    100 * df_bds['job_destruction_deaths'] / df_bds['denom']
)

df_bds['job_destruction_rate'] = (
    100 * df_bds['job_destruction'] / df_bds['denom']
)
df_bds['estabs_entry_rate'] = (
    100 * df_bds['estabs_entry'] / df_bds['estabs']
)

df_bds['estabs_exit_rate'] = (
    100 * df_bds['estabs_exit'] / df_bds['estabs']
)

df_bds['net_job_creation_rate'] = (
    df_bds['job_creation_rate'] -
    df_bds['job_destruction_rate']
)

df_bds['reallocation_rate'] = (
    df_bds['job_creation_rate'] +
    df_bds['job_destruction_rate'] -
    abs(df_bds['net_job_creation_rate'])
)

In [11]:
# Rechecking for Missing Entries
df_bds.isnull().sum()

year                               0
st                                 0
sector                             0
fage                               0
firms                              0
estabs                             0
emp                                0
denom                              0
estabs_entry                       0
estabs_entry_rate              12003
estabs_exit                    44574
estabs_exit_rate               55724
job_creation                   44574
job_creation_births                0
job_creation_continuers        44574
job_creation_rate_births       11047
job_creation_rate              54822
job_destruction                44574
job_destruction_deaths         44574
job_destruction_continuers     44574
job_destruction_rate_deaths    54822
job_destruction_rate           54822
net_job_creation               44574
net_job_creation_rate          54822
reallocation_rate              54822
firmdeath_firms                44574
firmdeath_estabs               44574
firmdeath_emp                  44574
sector_name                        0
state_abbr                         0
dtype: int64

In [12]:
# Checking percentge still missing
(df_bds.isnull().sum() / len(df_bds)) * 100

year                            0.000000
st                              0.000000
sector                          0.000000
fage                            0.000000
firms                           0.000000
estabs                          0.000000
emp                             0.000000
denom                           0.000000
estabs_entry                    0.000000
estabs_entry_rate               2.244021
estabs_exit                     8.333333
estabs_exit_rate               10.417882
job_creation                    8.333333
job_creation_births             0.000000
job_creation_continuers         8.333333
job_creation_rate_births        2.065292
job_creation_rate              10.249248
job_destruction                 8.333333
job_destruction_deaths          8.333333
job_destruction_continuers      8.333333
job_destruction_rate_deaths    10.249248
job_destruction_rate           10.249248
net_job_creation                8.333333
net_job_creation_rate          10.249248
reallocation_rate              10.249248
firmdeath_firms                 8.333333
firmdeath_estabs                8.333333
firmdeath_emp                   8.333333
sector_name                     0.000000
state_abbr                      0.000000
dtype: float64

The imputation approach through time-series interpolation aimed at imputing only the base variables. However, when values are missing across successive time periods, the interplation returns NAs; this represents the case for base variables still containing missing entires. For the derived variables, where the base variables are not imputed or are 0, the derived variables is computed to NA.
The remaining missing entries across variables show that the missingness does not exceed 11%. Given the small percentage of missingness remaining, the records with missing entries were removed as below.

In [23]:
# Removing 11% missing entries across columns
df_bds = df_bds.dropna()

**Federal Researve of the United States (FRED)**: Median Household Income by State from 1984-2024 containing 2050 entries.

In [13]:
# Getting state Abbreviations
states = [
    'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA',
    'HI','ID','IL','IN','IA','KS','KY','LA','ME','MD',
    'MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ',
    'NM','NY','NC','ND','OH','OK','OR','PA','RI','SC',
    'SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'
]
# Initializing Empty Dataset for Storage
df_mhi = []
# Looping over states to get data for all states
for s in states:
    series_id = f"MEHOINUS{s}A672N"
    # FRED API url for Median Household Income
    url = f"https://fred.stlouisfed.org/graph/fredgraph.csv?id={series_id}"
    df = pd.read_csv(url)
    df['state'] = s
    df_mhi .append(df)
# Combining Datasets
df_mhi_full = pd.concat(df_mhi)
# Data Overview
df_mhi_full.head()

,observation_date,MEHOINUSALA672N,state,MEHOINUSAKA672N,MEHOINUSAZA672N,MEHOINUSARA672N,MEHOINUSCAA672N,MEHOINUSCOA672N,MEHOINUSCTA672N,MEHOINUSDEA672N,...,MEHOINUSSDA672N,MEHOINUSTNA672N,MEHOINUSTXA672N,MEHOINUSUTA672N,MEHOINUSVTA672N,MEHOINUSVAA672N,MEHOINUSWAA672N,MEHOINUSWVA672N,MEHOINUSWIA672N,MEHOINUSWYA672N
0,1984-01-01,46660.0,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1985-01-01,47790.0,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1986-01-01,49070.0,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1987-01-01,48960.0,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1988-01-01,47720.0,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Checking Data info
df_mhi_full.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2050 entries, 0 to 40
Data columns (total 52 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  2050 non-null   object
 1   MEHOINUSALA672N   41 non-null     float64
 2   state             2050 non-null   object
 3   MEHOINUSAKA672N   41 non-null     float64
 4   MEHOINUSAZA672N   41 non-null     float64
 5   MEHOINUSARA672N   41 non-null     float64
 6   MEHOINUSCAA672N   41 non-null     float64
 7   MEHOINUSCOA672N   41 non-null     float64
 8   MEHOINUSCTA672N   41 non-null     float64
 9   MEHOINUSDEA672N   41 non-null     float64
 10  MEHOINUSFLA672N   41 non-null     float64
 11  MEHOINUSGAA672N   41 non-null     float64
 12  MEHOINUSHIA672N   41 non-null     float64
 13  MEHOINUSIDA672N   41 non-null     float64
 14  MEHOINUSILA672N   41 non-null     float64
 15  MEHOINUSINA672N   41 non-null     float64
 16  MEHOINUSIAA672N   41 non-null     float64
 17  MEHOINUSKSA672N   41 non-null     float64
 18  MEHOINUSKYA672N   41 non-null     float64
 19  MEHOINUSLAA672N   41 non-null     float64
 20  MEHOINUSMEA672N   41 non-null     float64
 21  MEHOINUSMDA672N   41 non-null     float64
 22  MEHOINUSMAA672N   41 non-null     float64
 23  MEHOINUSMIA672N   41 non-null     float64
 24  MEHOINUSMNA672N   41 non-null     float64
 25  MEHOINUSMSA672N   41 non-null     float64
 26  MEHOINUSMOA672N   41 non-null     float64
 27  MEHOINUSMTA672N   41 non-null     float64
 28  MEHOINUSNEA672N   41 non-null     float64
 29  MEHOINUSNVA672N   41 non-null     float64
 30  MEHOINUSNHA672N   41 non-null     float64
 31  MEHOINUSNJA672N   41 non-null     float64
 32  MEHOINUSNMA672N   41 non-null     float64
 33  MEHOINUSNYA672N   41 non-null     float64
 34  MEHOINUSNCA672N   41 non-null     float64
 35  MEHOINUSNDA672N   41 non-null     float64
 36  MEHOINUSOHA672N   41 non-null     float64
 37  MEHOINUSOKA672N   41 non-null     float64
 38  MEHOINUSORA672N   41 non-null     float64
 39  MEHOINUSPAA672N   41 non-null     float64
 40  MEHOINUSRIA672N   41 non-null     float64
 41  MEHOINUSSCA672N   41 non-null     float64
 42  MEHOINUSSDA672N   41 non-null     float64
 43  MEHOINUSTNA672N   41 non-null     float64
 44  MEHOINUSTXA672N   41 non-null     float64
 45  MEHOINUSUTA672N   41 non-null     float64
 46  MEHOINUSVTA672N   41 non-null     float64
 47  MEHOINUSVAA672N   41 non-null     float64
 48  MEHOINUSWAA672N   41 non-null     float64
 49  MEHOINUSWVA672N   41 non-null     float64
 50  MEHOINUSWIA672N   41 non-null     float64
 51  MEHOINUSWYA672N   41 non-null     float64
dtypes: float64(50), object(2)
memory usage: 848.8+ KB

Data Cleaning: Since the datasets for each of the states was collected separately, the data required cleaning to bring all the median household income to one column.

In [15]:
# Using date column as identifier column
id_col = 'observation_date'

# Melting all state columns into long format
df_long_mhi = df_mhi_full.melt(
    id_vars=[id_col],
    value_vars=[col for col in df_mhi_full.columns if col.startswith('MEHOINUS')],
    var_name='series_id',
    value_name='income'
)

# Removing missing rows
df_long_mhi = df_long_mhi.dropna(subset=['income'])
print(df_long_mhi.head())

# Extracting state abbreviation from series id
df_long_mhi['state_abbr'] = df_long_mhi['series_id'].str.extract(r'MEHOINUS([A-Z]{2})A672N')
df_long_mhi = df_long_mhi[
    ['observation_date', 'state_abbr', 'income']
].reset_index(drop=True)
print(df_long_mhi.head())

  observation_date        series_id   income
0       1984-01-01  MEHOINUSALA672N  46660.0
1       1985-01-01  MEHOINUSALA672N  47790.0
2       1986-01-01  MEHOINUSALA672N  49070.0
3       1987-01-01  MEHOINUSALA672N  48960.0
4       1988-01-01  MEHOINUSALA672N  47720.0
  observation_date state_abbr   income
0       1984-01-01         AL  46660.0
1       1985-01-01         AL  47790.0
2       1986-01-01         AL  49070.0
3       1987-01-01         AL  48960.0
4       1988-01-01         AL  47720.0

In [16]:
# Feature Engineering: Creating year variable
df_long_mhi['observation_date'] = pd.to_datetime(df_long_mhi['observation_date'])
df_long_mhi['year'] = df_long_mhi['observation_date'].dt.year
# Dropping observation data
df_long_mhi = df_long_mhi.drop(columns=['observation_date'])
# Data Overview
df_long_mhi.head()

  state_abbr   income  year
0         AL  46660.0  1984
1         AL  47790.0  1985
2         AL  49070.0  1986
3         AL  48960.0  1987
4         AL  47720.0  1988

In [17]:
# Checking Data Information
df_long_mhi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   state_abbr  2050 non-null   object
 1   income      2050 non-null   float64
 2   year        2050 non-null   int32
dtypes: float64(1), int32(1), object(1)
memory usage: 40.2+ KB

**Federal Researve of the United States (FRED)**: Population by State from 1900-2025 containing 6200 entries.

In [18]:
# Initializing empty dataframe for storage
df_pop = []
# Looping over states
for s in states:
    series_id = f"{s}POP"
    # FRED API url for Population Estimates
    url = f"https://fred.stlouisfed.org/graph/fredgraph.csv?id={series_id}"
    df = pd.read_csv(url)
    df.columns = ['observation_date', 'population']
    df['state'] = s
    df_pop.append(df)
# Combining Datasets
df_pop_full = pd.concat(df_pop, ignore_index=True)
# Data Overview
df_pop_full.head()

  observation_date  population state
0       1900-01-01      1830.0    AL
1       1901-01-01      1907.0    AL
2       1902-01-01      1935.0    AL
3       1903-01-01      1957.0    AL
4       1904-01-01      1978.0    AL

In [19]:
# Checking Data info
df_pop_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6200 entries, 0 to 6199
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  6200 non-null   object
 1   population        6200 non-null   float64
 2   state             6200 non-null   object
dtypes: float64(1), object(2)
memory usage: 145.4+ KB

In [20]:
# Feature Engineering: Creating year variable
df_pop_full['observation_date'] = pd.to_datetime(df_pop_full['observation_date'])
df_pop_full['year'] = df_pop_full['observation_date'].dt.year
# Dropping observation data
df_pop_full = df_pop_full.drop(columns=['observation_date'])
# Data Overview
df_pop_full.head()

   population state  year
0      1830.0    AL  1900
1      1907.0    AL  1901
2      1935.0    AL  1902
3      1957.0    AL  1903
4      1978.0    AL  1904

In [21]:
# Checking Data Information
df_pop_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6200 entries, 0 to 6199
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  6200 non-null   float64
 1   state       6200 non-null   object
 2   year        6200 non-null   int32
dtypes: float64(1), int32(1), object(1)
memory usage: 121.2+ KB

# Data Merging

Across all three data sets (Business Closures, Median Household Income and Population) the year and state variables are present. Inorder to preserve the firm age and sector variables, the Median Household Income and Population will be merged to the Business Closures dataset.

In [24]:
# Getting common states across the three datasets to keep states and not territories
common_states = set(df_bds['state_abbr']) \
    .intersection(df_long_mhi['state_abbr']) \
    .intersection(df_pop_full['state'])

# Filtering the three datasets for common states
df_bds_filtered = df_bds[
    df_bds['state_abbr'].isin(common_states)
]

df_long_mhi_filtered = df_long_mhi[
    df_long_mhi['state_abbr'].isin(common_states)
]

df_pop_filtered = df_pop_full[
    df_pop_full['state'].isin(common_states)
]

# Merging the datasets by state and year
df_merged = df_bds_filtered.merge(
    df_long_mhi_filtered,
    on=['state_abbr', 'year'],
    how='left'
)

df_merged = df_merged.merge(
    df_pop_filtered.rename(columns={'state': 'state_abbr'}),
    on=['state_abbr', 'year'],
    how='left'
)

# Checking data info
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470989 entries, 0 to 470988
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   year                         470989 non-null  int64
 1   st                           470989 non-null  int64
 2   sector                       470989 non-null  category
 3   fage                         470989 non-null  category
 4   firms                        470989 non-null  float64
 5   estabs                       470989 non-null  float64
 6   emp                          470989 non-null  float64
 7   denom                        470989 non-null  float64
 8   estabs_entry                 470989 non-null  float64
 9   estabs_entry_rate            470989 non-null  float64
 10  estabs_exit                  470989 non-null  float64
 11  estabs_exit_rate             470989 non-null  float64
 12  job_creation                 470989 non-null  float64
 13  job_creation_births          470989 non-null  float64
 14  job_creation_continuers      470989 non-null  float64
 15  job_creation_rate_births     470989 non-null  float64
 16  job_creation_rate            470989 non-null  float64
 17  job_destruction              470989 non-null  float64
 18  job_destruction_deaths       470989 non-null  float64
 19  job_destruction_continuers   470989 non-null  float64
 20  job_destruction_rate_deaths  470989 non-null  float64
 21  job_destruction_rate         470989 non-null  float64
 22  net_job_creation             470989 non-null  float64
 23  net_job_creation_rate        470989 non-null  float64
 24  reallocation_rate            470989 non-null  float64
 25  firmdeath_firms              470989 non-null  float64
 26  firmdeath_estabs             470989 non-null  float64
 27  firmdeath_emp                470989 non-null  float64
 28  sector_name                  470989 non-null  category
 29  state_abbr                   470989 non-null  object
 30  income                       409643 non-null  float64
 31  population                   470989 non-null  float64
dtypes: category(3), float64(26), int64(2), object(1)
memory usage: 105.6+ MB

In [25]:
# Saving Datasets
df_bds.to_csv("df_bds.csv")
df_long_mhi.to_csv("df_long_mhi.csv")
df_pop_full.to_csv("df_pop_full.csv")
df_merged.to_csv("df_merged.csv")